version: '3'
services:
  agent:
    container_name: rookout-agent
    environment:
      ROOKOUT_TOKEN: YOUR_TOKEN_HERE
    image: "rookout/agent"

  app:
    build: .
    container_name: rookout-demo-app
    environment:
      ROOKOUT_AGENT_HOST: agent
    ports:
      - 7000:7000
    command:  java  -javaagent:rook.jar -jar target/rookoutDemo-1.0.0.jar


